"""added refresh token model

Revision ID: ed6ac5ca6deb
Revises: 
Create Date: 2025-12-03 23:34:02.642899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6ac5ca6deb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('refresh_token_id', sa.UUID(), nullable=False, comment='primary uuid for the refresh token row'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='foreign key to users.user_id'),
    sa.Column('token_hash', sa.String(), nullable=False, comment='hashed refresh token (e.g. HMAC or bcrypt/sha256 of token)'),
    sa.Column('user_agent', sa.String(), nullable=True, comment='user agent of the device/browser (optional)'),
    sa.Column('ip_address', sa.String(), nullable=True, comment='ip address when token was issued (optional)'),
    sa.Column('is_valid', sa.Boolean(), nullable=False, comment='whether this refresh token is currently valid (revoke on logout)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='creation timestamp'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='last update timestamp'),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='explicit expiry (optional if you handle expiry in app logic)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('refresh_token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_token', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_token')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
